### ISSUE TITLE
Can kind2 check this kind of code?

### ISSUE THREAD

**Issue by stanislaw** [kind2-mc/kind2#517]
Hello,

I am learning on the course Formal Software Verification. This week is about model checking and one of the tasks suggests me to use a tool of my own choice to prove if the following code is valid or not. I am wondering if I could accomplish this task with kind2.

I have installed the Docker image and can run the example I got from doc/usr/content/2_input. However, the tutorials are not enough for me to understand the following:

- how is global state modeled? how do I make 'beam' variable to persist when the line like `Set beam = B` is called?
- how to model the "randomness" in the order in which the functions `setBeam` and `setPlate` are executed (to ensure all combinations of states/plates are covered)?
- finally how to assign the `OK = ` value which should be equal to `not (plate = 2 and beam 2)`?

P.S. I am very new to model checking. Still, I hope I am not asking something completely dumb and simple. 

Thanks.

---

## Cancer treatment machine

> I am building a cancer treatment machine. The machine can emit two types of beams; for simplicity let’s just call them A and B. There are two different plates that can be placed in front of the beam; let’s call them 1 and 2. When you turn the machine on it always starts ups with beam set to A and plate set to 1. That is the initial state.

> For safety reasons we never want the machine to be at beam B and plate 2. If this every happens a deadline dose of radiation will be emitted and it will kill the patient. But all of the other combinations of beams and plates are valid.

> I have a developer write code to automate this machine. He claims that his software will prevent the machine from ever being in state beam = A and plate = 2.

> Here is his code. Use Model Checking to software this problem.

```
Method setBeam(str beamType)
     If beamType = B and plate = 1
          Set beam = B
     Else Set beam = A
Method setPlate(int plateType)
     If plateType = 2 and beam = A
          Set plate = 2
     Else Set plate = 1  
```

> Is he correct?

**Comment by daniel-larraz** [comment]
Hello Stanislav,

Yes, the system and the property can be modeled in Lustre, the [input language](http://kind.cs.uiowa.edu/kind2_user_doc/#n3801905-lustre-input) of Kind 2, and be checked by the tool. In order to get a better understanding of the language, I encourage you to read the first chapter of the [Lustre v4 tutorial](http://www-verimag.imag.fr/DIST-TOOLS/SYNCHRONE/lustre-v4/distrib/lustre_tutorial.pdf). The tutorial should answer your first question.

If you model beamType and plateType as input streams of your system, Kind 2 will only prove the property safe if there is no sequence of input values that leads to the violation of the property. Otherwise, Kind 2 will give you a counterexample. You can faithfully model the type of a beam and a plate by declaring a new enumeration and subrange:
```
type beam_t = enum {A, B};
type plate_t = subrange [1, 2] of int;
```
Then the property to be checked can be concisely specified with the following annotation:
```
--%PROPERTY not (beam = A and plate = 2);
```
If you need more help with the Lustre model, just send me an email: daniel-larraz (at) uiowa (dot) edu

Best regards,
Daniel
