### ISSUE TITLE
Asserts in sub-nodes do not produce proof obligations

### ISSUE THREAD

**Issue by amosr** [kind2-mc/kind2#595]
Hi,

I'm a bit confused by the behaviour of "assert". I expected it to act more like "assume", in that it would be assumed to be true while verifying the node containing the assertion, but would be required to be shown to be true wherever the node is used. At the moment, it seems to assume it to be true in both cases. The documentation doesn't really explain assert, so I don't know whether this is me not understanding the purpose of assert, or a bug in assert.

Here is a concrete example:
```
node weird_plus(a, b : int) returns (o : int)
let
  assert a = b;
  o = a * 2;
  --%PROPERTY o = a + b;
tel

node should_fail(a, b : int) returns (o : int)
/*@contract
  assume a <> b;
  guarantee o = a + b;
*/
let
  o = weird_plus(a, b);
tel
```

Node `weird_plus` asserts that both inputs are equal and adds them together by doubling one of the inputs. This property succeeds, as expected.

Then, the node `should_fail` assumes that the two inputs are different, and tries to use `weird_plus` to add them together. I expected this use of `weird_plus` to fail because `weird_plus` has the precondition that `a = b`, which is not true here. However, the property succeeds.

Is this the expected behaviour?

Thanks,
Amos

**Comment by daniel-larraz** [comment]
Hi Amos,

Yes, it is the expected behavior. The name of the `assert` command in Lustre is unfortunate. The `assert` command behaves as an `assume` in other languages, that is, Kind 2 assumes that the condition holds but it **doesn't check** it really holds. For this reason, we discourage users from using the `assert` command.

In your concrete example, the guarantee of the node `should_fail` is trivially satisfied because there is no trace where `a` and `b` are equal and distinct at the same time. Sometimes the BMC engine detects this situation and reports it as a warning:

`<Warning> BMC Initial state is unsat, the system has no reachable states.`

We recommend to rewrite your model using only contracts:
```
node weird_plus(a, b : int) returns (o : int)
/*@contract
  assume a = b;
  guarantee o = a + b;
*/
let
  o = a * 2;
tel

node should_fail(a, b : int) returns (o : int)
/*@contract
  assume a <> b;
  guarantee o = a + b;
*/
let
  o = weird_plus(a, b);
tel
```
Using the new model, Kind 2 will report the guarantee as invalid. Moreover, if you run Kind 2 passing these arguments `--compositional true --modular true`, which enables the [compositional and modular analysis](https://kind.cs.uiowa.edu/kind2_user_doc/1_techniques/1_techniques.html#compositional-reasoning), Kind 2 will report that node `weird_plus` satisfies its contract, but node `should_fail` doesn't satisfy `weird_plus`'s assumption.

Daniel

**Comment by amosr** [comment]
Hi Daniel,

Ah, fair enough. Is this behaviour is inherited from Lustre/Lesar?

Just for posterity's sake, I'll add a few sentences about `assert` to the user documentation, noting that it's discouraged and potentially confusing, and send through a PR tomorrow/soon if you don't mind. (Not sure exactly where it fits best in the documentation, so if you have opinions let me know, otherwise I'll just try to find somewhere)

Amos
