### ISSUE TITLE
What Cannot generalize quantified terms means?

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#634]
Hi Daniel,

I have problems with an example full of quantifiers and keep getting weird results with this error:
<Error> Cannot generalize quantified terms.
<Error> Runtime failure in property directed reachability: Cannot generalize quantified terms.

Do you have any clue what may causes this problem?

Thanks,
Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

This error means the PDR/IC3 engine cannot continue running because the function that generalizes counterexamples to induction in Kind 2 does not support properties that includes quantifiers. You can get rid of this error message by disabling the IC3 engine (`--disable IC3`).

Best,
Daniel

**Comment by daniel-larraz** [comment]
Closing this issue. Please feel free to open a new one if you have more questions.
