### ISSUE TITLE
Property / test coverage (feature request)

### ISSUE THREAD

**Issue by amosr** [kind2-mc/kind2#744]
Hi Daniel,

We were wondering whether it's possible to compute some sort of "property coverage", like test coverage; roughly, which definitions affect the behaviour of a function but do not affect any of the properties. I wonder whether you have any thoughts on coverage.

The coverage problem sounds like a similar dependency analysis to slicing to me. Maybe it is possible to slice the function wrt all of the properties, and then mark those definitions that remain in the sliced version as 'covered'. Would you be interested in this feature if we were able to implement it?

I also read Vassil Todorov's thesis earlier this year but I can't find it again now, unfortunately. Vassil described a trick where you delete each definition and see which properties fail. If no properties fail, then the definition is not covered by a property. I guess this is equivalent to replacing the definitions with nondeterministic values. This sounds neat, but I worry that it will be too slow to compute. The simple version of just checking dependencies may suffice for us, for now.

Amos

**Comment by daniel-larraz** [comment]
Hi Amos,

Yes, it is possible to compute it, and Kind 2 already offers the functionality necessary to do it. Given a set of properties, any definition can be classified in one of three categories: _must_ definitions, _may_ definitions, or _irrelevant_ definitions. Must definitions are definitions which are required for proving the properties in every case, May definitions are definitions which are relevant to at least one proof of the properties but are not strictly necessary for their satisfaction, and Irrelevant definitions are definitions which does not affect the satisfaction of the properties at all.

Given the previous categorization, there exists two common notions of coverage: may-coverage and must-coverage. People are usually interested in must-coverage, which is equivalent to non-deterministic mutation coverage. To compute the set of MUST _elements_ for the valid properties of a model, you can run Kind 2 as follows:  `--ivc true --ivc_must_set true`. I said _elements_, because definitions/equations are only one of the model elements you can consider in the computation. By default, Kind 2 considers top-level assumptions, subcomponent's guarantees, stateful equations, and node calls. You can select a single category with the `--ivc_category` flag. Kind 2 assumes that any element outside the selected category is always present in the system. If the options above are used, Kind 2 will compute the must set and a minimal inductive validity core (MIVC) after checking the properties. A MIVC is a set of elements that are sufficient to prove the valid properties. If all elements are must elements, both sets will be the same. Otherwise, more than one MIVC exists and the presented MIVC will contain May elements. To compute all the MIVCs, you can pass `--ivc_all true`. For further details, please see the [Inductive Validity Core](https://kind.cs.uiowa.edu/kind2_user_doc/9_other/10_inductive_validity_core.html) section in Kind 2 documentation. You may be also interested in the computation of [Minimal Cut Sets](https://kind.cs.uiowa.edu/kind2_user_doc/9_other/11_minimal_cut_set.html).

Daniel

**Comment by amosr** [comment]
Hi Daniel,
Thanks for your detailed explanation. I only just had a chance to try it out – it looks like it provides all the information we want, so I'll close this.

Thanks!
Amos
